# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_queue_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatablejob',
            name='result_ttl',
            field=models.IntegerField(blank=True, help_text='The TTL value (in seconds) of the job result. -1: Result never expires, you should delete jobs manually. 0: Result gets deleted immediately. >0: Result expires after n seconds.', null=True, verbose_name='result ttl'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='result_ttl',
            field=models.IntegerField(blank=True, help_text='The TTL value (in seconds) of the job result. -1: Result never expires, you should delete jobs manually. 0: Result gets deleted immediately. >0: Result expires after n seconds.', null=True, verbose_name='result ttl'),
        ),
    ]
