# Generated by Django 4.1.7 on 2023-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': ' Workers',
                'permissions': [['view', 'Access admin page']],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'default_permissions': (), 'managed': False, 'permissions': [['view', 'Access admin page']], 'verbose_name_plural': ' Queues'},
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='at_front',
            field=models.BooleanField(blank=True, default=False, help_text='When scheduling the job, add it in the front of the queue', null=True, verbose_name='At front'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Should job be scheduled? This field is useful to keep past jobs that should no longer be scheduled', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='job_id',
            field=models.CharField(blank=True, editable=False, help_text='Current job_id on queue', max_length=128, null=True, verbose_name='job id'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='repeat',
            field=models.PositiveIntegerField(blank=True, help_text='Number of times to repeat the job', null=True, verbose_name='repeat'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='at_front',
            field=models.BooleanField(blank=True, default=False, help_text='When scheduling the job, add it in the front of the queue', null=True, verbose_name='At front'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Should job be scheduled? This field is useful to keep past jobs that should no longer be scheduled', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='job_id',
            field=models.CharField(blank=True, editable=False, help_text='Current job_id on queue', max_length=128, null=True, verbose_name='job id'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='repeat',
            field=models.PositiveIntegerField(blank=True, help_text='Number of times to repeat the job', null=True, verbose_name='repeat'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='at_front',
            field=models.BooleanField(blank=True, default=False, help_text='When scheduling the job, add it in the front of the queue', null=True, verbose_name='At front'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Should job be scheduled? This field is useful to keep past jobs that should no longer be scheduled', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='job_id',
            field=models.CharField(blank=True, editable=False, help_text='Current job_id on queue', max_length=128, null=True, verbose_name='job id'),
        ),
    ]
